// Определяем интерфейс
export interface Friends {
  id: number;
  status: boolean;
  name: string;
  avatar: string;
  location: {
    country: string;
    city: string;
  };
  dateOfBirth: string;
  education: string;
  webSite: string;
  occupation: string;
  interests: string;
  phoneNumber: string;
  email: string;
  socialMedia: {
    instagram?: string;
    twitter?: string;
    linkedin?: string;
  };
  statusText: string;
}

export const friendsData: Friends[] = [
  {
    id: 0,
    status: true,
    name: "Иван Иванов",
    // title: "На связи, пишите!",
    avatar: "https://i.ibb.co/1ZmNrYX/user-avatar-00.jpg",
    location: { country: "Россия", city: "Краснодар" },
    dateOfBirth: "1990-05-15",
    education:
      "Московский Государственный Университет, факультет вычислительной математики и кибернетики",
    webSite: "https://ivanivanov.com",
    occupation: "Разработчик программного обеспечения",
    interests: "Программирование, путешествия, чтение книг",
    phoneNumber: "+7 900 123 45 67",
    email: "ivan.ivanov@mail.ru",
    socialMedia: {
      instagram: "@ivan_ivanov",
      twitter: "@ivan_dev",
      linkedin: "linkedin.com/in/ivanivanov",
    },
    statusText: "На связи, пишите!",
  },
  {
    id: 1,
    status: false,
    name: "Алексей Иванов",
    // title: "Менеджер проектов",
    avatar: "https://i.ibb.co/9Gm3PLM/user-avatar-01.jpg",
    location: { country: "Россия", city: "Москва" },
    dateOfBirth: "1985-04-12",
    education: "МГУ, факультет экономики",
    webSite: "https://ivanov-projects.ru",
    occupation: "IT-компания",
    interests: "Путешествия, технологии, чтение",
    phoneNumber: "+7 900 123 45 67",
    email: "ivanov.alexey@mail.ru",
    socialMedia: {
      instagram: "@ivanov_alexey",
      twitter: "@alexey_ivanov",
      linkedin: "linkedin.com/in/alexey-ivanov",
    },
    statusText: "В данный момент не в сети",
  },
  {
    id: 2,
    status: true,
    name: "Екатерина Смирнова",
    // title: "Маркетолог",
    avatar: "https://i.ibb.co/6JN2kcJ/user-avatar-02.jpg",
    location: { country: "Россия", city: "Санкт-Петербург" },
    dateOfBirth: "1990-08-25",
    education: "СПбГУ, маркетинг",
    webSite: "https://smirnova-marketing.ru",
    occupation: "Рекламное агентство",
    interests: "Маркетинг, йога, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "smirnova.katya@gmail.com",
    socialMedia: {
      instagram: "@katya_smirnova",
      twitter: "@smirnova_k",
      linkedin: "linkedin.com/in/ekaterina-smirnova",
    },
    statusText: "Активна и онлайн",
  },
  {
    id: 3,
    status: false,
    name: "Дмитрий Кузнецов",
    // title: "Программист",
    avatar: "https://i.ibb.co/tb8qRNc/user-avatar-03.jpg",
    location: { country: "Россия", city: "Казань" },
    dateOfBirth: "1992-11-03",
    education: "КФУ, прикладная математика",
    webSite: "https://kuznetsov-dev.ru",
    occupation: "Фриланс",
    interests: "Программирование, киберспорт",
    phoneNumber: "+7 900 123 45 67",
    email: "d.kuznetsov@mail.ru",
    socialMedia: {
      instagram: "@dmitry.kuznetsov",
      twitter: "@kuznetsov_dev",
      linkedin: "linkedin.com/in/dmitry-kuznetsov",
    },
    statusText: "Не в сети в данный момент",
  },
  {
    id: 4,
    status: true,
    name: "Анна Петрова",
    // title: "Дизайнер",
    avatar: "https://i.ibb.co/sPSJfd3/user-avatar-04.jpg",
    location: { country: "Россия", city: "Екатеринбург" },
    dateOfBirth: "1988-06-19",
    education: "УрФУ, графический дизайн",
    webSite: "https://petrova-design.ru",
    occupation: "Дизайн-студия",
    interests: "Иллюстрация, фотография, искусство",
    phoneNumber: "+7 900 123 45 67",
    email: "petrova.anna@gmail.com",
    socialMedia: {
      instagram: "@anna_petrova_design",
      twitter: "@petrova_a",
      linkedin: "linkedin.com/in/anna-petrova",
    },
    statusText: "В сети и готова к работе",
  },
  {
    id: 5,
    status: false,
    name: "Игорь Соколов",
    // title: "Аналитик данных",
    avatar: "https://i.ibb.co/TKY9qTW/user-avatar-05.jpg",
    location: { country: "Россия", city: "Новосибирск" },
    dateOfBirth: "1995-02-15",
    education: "НГУ, анализ данных",
    webSite: "https://sokolov-data.ru",
    occupation: "IT-компания",
    interests: "Большие данные, шахматы",
    phoneNumber: "+7 900 123 45 67",
    email: "sokolov.igor@yandex.ru",
    socialMedia: {
      instagram: "@igor_sokolov",
      twitter: "@sokolov_data",
      linkedin: "linkedin.com/in/igor-sokolov",
    },
    statusText: "Не активен сейчас",
  },
  {
    id: 6,
    status: true,
    name: "Мария Орлова",
    // title: "HR-менеджер",
    avatar: "https://i.ibb.co/3MHMXV6/user-avatar-06.jpg",
    location: { country: "Россия", city: "Нижний Новгород" },
    dateOfBirth: "1987-09-14",
    education: "НИУ ВШЭ, управление персоналом",
    webSite: "https://orlova-hr.ru",
    occupation: "Корпорация HR Solutions",
    interests: "Книги, психология, фитнес",
    phoneNumber: "+7 900 123 45 67",
    email: "orlova.maria@mail.ru",
    socialMedia: {
      instagram: "@maria_hr",
      twitter: "@orlova_m",
      linkedin: "linkedin.com/in/maria-orlova",
    },
    statusText: "Всегда онлайн, пишите мне",
  },
  {
    id: 7,
    status: false,
    name: "Сергей Волков",
    // title: "Инженер",
    avatar: "https://i.ibb.co/p3fmNrV/user-avatar-07.jpg",
    location: { country: "Россия", city: "Самара" },
    dateOfBirth: "1983-01-22",
    education: "СамГТУ, машиностроение",
    webSite: "https://volkov-engineer.ru",
    occupation: "Производственное предприятие",
    interests: "Техника, рыбалка, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "volkov.sergey@mail.ru",
    socialMedia: {
      instagram: "@volkov_sergey",
      twitter: "@volkov_s",
      linkedin: "linkedin.com/in/sergey-volkov",
    },
    statusText: "Временно недоступен",
  },
  {
    id: 8,
    status: true,
    name: "Ольга Васильева",
    // title: "Финансовый аналитик",
    avatar: "https://i.ibb.co/KG9RhWQ/user-avatar-08.jpg",
    location: { country: "Россия", city: "Ростов-на-Дону" },
    dateOfBirth: "1991-05-18",
    education: "ЮФУ, финансы и кредит",
    webSite: "https://vasilieva-finance.ru",
    occupation: "Банк",
    interests: "Финансы, инвестиции, йога",
    phoneNumber: "+7 900 123 45 67",
    email: "vasilieva.olga@gmail.com",
    socialMedia: {
      instagram: "@olga_vas",
      twitter: "@vasilieva_o",
      linkedin: "linkedin.com/in/olga-vasilieva",
    },
    statusText: "Доступна для связи",
  },
  {
    id: 9,
    status: false,
    name: "Никита Захаров",
    // title: "Архитектор",
    avatar: "https://i.ibb.co/hBx5TH9/user-avatar-09.jpg",
    location: { country: "Россия", city: "Воронеж" },
    dateOfBirth: "1989-12-30",
    education: "ВГАСУ, архитектура",
    webSite: "https://zakharov-architecture.ru",
    occupation: "Архитектурное бюро",
    interests: "Дизайн, путешествия, скетчинг",
    phoneNumber: "+7 900 123 45 67",
    email: "zakharov.nikita@yandex.ru",
    socialMedia: {
      instagram: "@nikita_zakharov",
      twitter: "@zakharov_n",
      linkedin: "linkedin.com/in/nikita-zakharov",
    },
    statusText: "Нет в сети",
  },
  {
    id: 10,
    status: true,
    name: "Татьяна Белова",
    // title: "UX/UI дизайнер",
    avatar: "https://i.ibb.co/FVqnf9M/user-avatar-10.jpg",
    location: { country: "Россия", city: "Краснодар" },
    dateOfBirth: "1993-03-27",
    education: "КубГУ, дизайн",
    webSite: "https://belova-design.ru",
    occupation: "Фриланс",
    interests: "Дизайн, искусство, музыка",
    phoneNumber: "+7 900 123 45 67",
    email: "belova.tatyana@mail.ru",
    socialMedia: {
      instagram: "@tatiana_design",
      twitter: "@belova_t",
      linkedin: "linkedin.com/in/tatiana-belova",
    },
    statusText: "Всегда на связи",
  },

  {
    id: 11,
    status: false,
    name: "Ирина Коваленко",
    // title: "Маркетолог",
    avatar: "https://i.ibb.co/SVhHhtN/user-avatar-11.jpg",
    location: { country: "Россия", city: "Сочи" },
    dateOfBirth: "1990-07-02",
    education: "КНУ, маркетинг",
    webSite: "https://kovalenko-marketing.ua",
    occupation: "Рекламная компания",
    interests: "Маркетинг, музыка, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "kovalenko.irina@mail.ua",
    socialMedia: {
      instagram: "@irina_kovalenko",
      twitter: "@kovalenko_i",
      linkedin: "linkedin.com/in/irina-kovalenko",
    },
    statusText: "Не в сети",
  },
  {
    id: 12,
    status: true,
    name: "Петр Володин",
    // title: "Программист",
    avatar: "https://i.ibb.co/dfrG1nM/user-avatar-12.jpg",
    location: { country: "Беларусь", city: "Минск" },
    dateOfBirth: "1985-11-11",
    education: "БГУ, компьютерные науки",
    webSite: "https://volodin-dev.by",
    occupation: "Фриланс",
    interests: "Программирование, киберспорт, наука",
    phoneNumber: "+7 900 123 45 67",
    email: "volodin.petr@mail.by",
    socialMedia: {
      instagram: "@petr_volodin",
      twitter: "@volodin_p",
      linkedin: "linkedin.com/in/petr-volodin",
    },
    statusText: "Онлайн",
  },
  {
    id: 13,
    status: false,
    name: "Александр Новиков",
    // title: "Дизайнер",
    avatar: "https://i.ibb.co/48d19pW/user-avatar-13.jpg",
    location: { country: "Казахстан", city: "Алматы" },
    dateOfBirth: "1992-02-20",
    education: "КазНУ, графический дизайн",
    webSite: "https://novikov-design.kz",
    occupation: "Дизайн-студия",
    interests: "Дизайн, искусство, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "novikov.alexander@mail.kz",
    socialMedia: {
      instagram: "@novikov_design",
      twitter: "@novikov_a",
      linkedin: "linkedin.com/in/alexander-novikov",
    },
    statusText: "Не в сети",
  },
  {
    id: 14,
    status: true,
    name: "Ксения Соловьева",
    // title: "Менеджер по продажам",
    avatar: "https://i.ibb.co/MnF8gTN/user-avatar-14.jpg",
    location: { country: "Германия", city: "Берлин" },
    dateOfBirth: "1988-04-15",
    education: "Берлинский университет, бизнес-администрирование",
    webSite: "https://solovyeva-sales.de",
    occupation: "Продажи",
    interests: "Продажи, маркетинг, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "solovyeva.kseniya@mail.de",
    socialMedia: {
      instagram: "@ksenia_sales",
      twitter: "@solovyeva_k",
      linkedin: "linkedin.com/in/ksenia-solovyeva",
    },
    statusText: "Онлайн",
  },
  {
    id: 15,
    status: false,
    name: "Михаил Гончаров",
    // title: "Аналитик данных",
    avatar: "https://i.ibb.co/9rBjyYZ/user-avatar-15.jpg",
    location: { country: "Армения", city: "Ереван" },
    dateOfBirth: "1994-09-09",
    education: "Ереванский государственный университет, математика",
    webSite: "https://goncharov-data.am",
    occupation: "Аналитика данных",
    interests: "Данные, технологии, шахматы",
    phoneNumber: "+7 900 123 45 67",
    email: "goncharov.mikhail@mail.am",
    socialMedia: {
      instagram: "@mikhail_data",
      twitter: "@goncharov_m",
      linkedin: "linkedin.com/in/mikhail-goncharov",
    },
    statusText: "Не в сети",
  },
  {
    id: 16,
    status: true,
    name: "Лена Михайлова",
    // title: "Журналист",
    avatar: "https://i.ibb.co/zn2rcMM/user-avatar-16.jpg",
    location: { country: "США", city: "Нью-Йорк" },
    dateOfBirth: "1993-06-24",
    education: "Колумбийский университет, журналистика",
    webSite: "https://mikhaylova-journalist.com",
    occupation: "Медиа-компания",
    interests: "Журналистика, культура, социальные сети",
    phoneNumber: "+7 900 123 45 67",
    email: "mikhaylova.lena@mail.com",
    socialMedia: {
      instagram: "@lena_mikhaylova",
      twitter: "@mikhaylova_l",
      linkedin: "linkedin.com/in/lena-mikhaylova",
    },
    statusText: "Онлайн",
  },
  {
    id: 17,
    status: false,
    name: "Кирилл Федоров",
    // title: "Проект-менеджер",
    avatar: "https://i.ibb.co/CMcwwkm/user-avatar-17.jpg",
    location: { country: "Грузия", city: "Тбилиси" },
    dateOfBirth: "1986-12-18",
    education: "Тбилисский государственный университет, управление проектами",
    webSite: "https://fedorov-projects.ge",
    occupation: "Проектная организация",
    interests: "Управление проектами, фильмы, спорт",
    phoneNumber: "+7 900 123 45 67",
    email: "fedorov.kirill@mail.ge",
    socialMedia: {
      instagram: "@kirill_fedorov",
      twitter: "@fedorov_k",
      linkedin: "linkedin.com/in/kirill-fedorov",
    },
    statusText: "Не в сети",
  },
  {
    id: 18,
    status: true,
    name: "Динара Ахметова",
    // title: "Финансовый консультант",
    avatar: "https://i.ibb.co/VTJs5Rx/user-avatar-18.jpg",
    location: { country: "Казахстан", city: "Алматы" },
    dateOfBirth: "1988-02-13",
    education: "КазНУ, финансы",
    webSite: "https://ahmetova-finance.kz",
    occupation: "Финансовая консультация",
    interests: "Инвестиции, финансовое планирование",
    phoneNumber: "+7 900 123 45 67",
    email: "ahmetova.dinara@mail.kz",
    socialMedia: {
      instagram: "@dinara_finance",
      twitter: "@ahmetova_d",
      linkedin: "linkedin.com/in/dinara-ahmetova",
    },
    statusText: "Онлайн",
  },
  {
    id: 19,
    status: false,
    name: "Дмитрий Лебедев",
    // title: "Арт-директор",
    avatar: "https://i.ibb.co/WxpV5wN/user-avatar-19.jpg",
    location: { country: "Латвия", city: "Рига" },
    dateOfBirth: "1989-05-30",
    education: "Рижская академия художеств, дизайн",
    webSite: "https://lebedev-art.lv",
    occupation: "Арт-студия",
    interests: "Искусство, коллекционирование, выставки",
    phoneNumber: "+7 900 123 45 67",
    email: "lebedev.dmitry@mail.lv",
    socialMedia: {
      instagram: "@dmitry_art",
      twitter: "@lebedev_d",
      linkedin: "linkedin.com/in/dmitry-lebedev",
    },
    statusText: "Не в сети",
  },
  {
    id: 20,
    status: true,
    name: "Анастасия Петрова",
    // title: "Веб-разработчик",
    avatar: "https://i.ibb.co/RDyF02W/user-avatar-20.jpg",
    location: { country: "Россия", city: "Уфа" },
    dateOfBirth: "1995-03-03",
    education: "ХНУ, информатика",
    webSite: "https://petrova-web.com",
    occupation: "Веб-разработка",
    interests: "Программирование, путешествия, дизайн",
    phoneNumber: "+7 900 123 45 67",
    email: "petrova.anastasia@mail.ua",
    socialMedia: {
      instagram: "@anastasia_web",
      twitter: "@petrova_a",
      linkedin: "linkedin.com/in/anastasia-petrova",
    },
    statusText: "Онлайн",
  },
  {
    id: 21,
    status: false,
    name: "Владимир Иванов",
    // title: "Менеджер по продажам",
    avatar: "https://i.ibb.co/VSgYB4f/user-avatar-21.jpg",
    location: { country: "Россия", city: "Москва" },
    dateOfBirth: "1990-01-15",
    education: "МГИМО, экономика",
    webSite: "https://ivanov-sales.ru",
    occupation: "Продажи",
    interests: "Бизнес, путешествия, спорт",
    phoneNumber: "+7 900 123 45 67",
    email: "ivanov.vladimir@mail.ru",
    socialMedia: {
      instagram: "@vladimir_sales",
      twitter: "@ivanov_v",
      linkedin: "linkedin.com/in/vladimir-ivanov",
    },
    statusText: "Не в сети",
  },
  {
    id: 22,
    status: true,
    name: "Ольга Петрова",
    // title: "HR-менеджер",
    avatar: "https://i.ibb.co/2s2S33g/user-avatar-22.jpg",
    location: { country: "Казахстан", city: "Алматы" },
    dateOfBirth: "1985-09-21",
    education: "КазНУ, психология",
    webSite: "https://petrova-hr.kz",
    occupation: "HR",
    interests: "Подбор персонала, психология, чтение",
    phoneNumber: "+7 900 123 45 67",
    email: "petrova.olga@mail.kz",
    socialMedia: {
      instagram: "@olga_hr",
      twitter: "@petrova_o",
      linkedin: "linkedin.com/in/olga-petrova",
    },
    statusText: "Онлайн",
  },
  {
    id: 23,
    status: false,
    name: "Денис Козлов",
    // title: "Программист",
    avatar: "https://i.ibb.co/vkC9Hct/user-avatar-23.jpg",
    location: { country: "Беларусь", city: "Минск" },
    dateOfBirth: "1992-02-10",
    education: "БелГУ, IT",
    webSite: "https://kozlov-dev.by",
    occupation: "Фриланс",
    interests: "Программирование, кино, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "kozlov.denis@mail.by",
    socialMedia: {
      instagram: "@denis_kozlov",
      twitter: "@kozlov_d",
      linkedin: "linkedin.com/in/denis-kozlov",
    },
    statusText: "Не в сети",
  },
  {
    id: 24,
    status: true,
    name: "Анна Смирнова",
    // title: "Дизайнер",
    avatar: "https://i.ibb.co/C12jhLb/user-avatar-24.jpg",
    location: { country: "Германия", city: "Берлин" },
    dateOfBirth: "1987-04-03",
    education: "Берлинский университет, искусство и дизайн",
    webSite: "https://smirnova-design.de",
    occupation: "Дизайнер",
    interests: "Графический дизайн, искусство, музыка",
    phoneNumber: "+7 900 123 45 67",
    email: "smirnova.anna@mail.de",
    socialMedia: {
      instagram: "@anna_design",
      twitter: "@smirnova_a",
      linkedin: "linkedin.com/in/anna-smirnova",
    },
    statusText: "Онлайн",
  },
  {
    id: 25,
    status: false,
    name: "Максим Григорьев",
    // title: "Маркетолог",
    avatar: "https://i.ibb.co/7tTscBF/user-avatar-25.jpg",
    location: { country: "Армения", city: "Ереван" },
    dateOfBirth: "1994-03-15",
    education: "ЕГУ, маркетинг",
    webSite: "https://grigoryev-marketing.am",
    occupation: "Маркетинг",
    interests: "Маркетинг, анализ данных, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "grigoryev.maxim@mail.am",
    socialMedia: {
      instagram: "@maxim_grigoryev",
      twitter: "@grigoryev_m",
      linkedin: "linkedin.com/in/maxim-grigoryev",
    },
    statusText: "Не в сети",
  },
  {
    id: 26,
    status: true,
    name: "Елена Морозова",
    // title: "Веб-разработчик",
    avatar: "https://i.ibb.co/7JXKr9H/user-avatar-26.jpg",
    location: { country: "США", city: "Нью-Йорк" },
    dateOfBirth: "1990-06-10",
    education: "Колумбийский университет, компьютерные науки",
    webSite: "https://morozova-web.com",
    occupation: "Веб-разработка",
    interests: "Технологии, музыка, фильмы",
    phoneNumber: "+7 900 123 45 67",
    email: "morozova.elena@mail.com",
    socialMedia: {
      instagram: "@elena_web",
      twitter: "@morozova_e",
      linkedin: "linkedin.com/in/elena-morozova",
    },
    statusText: "Онлайн",
  },
  {
    id: 27,
    status: false,
    name: "Игорь Сидоров",
    // title: "Финансовый аналитик",
    avatar: "https://i.ibb.co/vYkZwgD/user-avatar-27.jpg",
    location: { country: "Латвия", city: "Рига" },
    dateOfBirth: "1988-07-25",
    education: "Рижская школа бизнеса, экономика",
    webSite: "https://sidorov-finance.lv",
    occupation: "Аналитика",
    interests: "Финансовые технологии, спорт",
    phoneNumber: "+7 900 123 45 67",
    email: "sidorov.igor@mail.lv",
    socialMedia: {
      instagram: "@igor_sidorov",
      twitter: "@sidorov_i",
      linkedin: "linkedin.com/in/igor-sidorov",
    },
    statusText: "Не в сети",
  },
  {
    id: 28,
    status: true,
    name: "Александра Коваленко",
    // title: "Рекрутер",
    avatar: "https://i.ibb.co/vsWT86v/user-avatar-28.jpg",
    location: { country: "Грузия", city: "Тбилиси" },
    dateOfBirth: "1993-08-11",
    education: "Тбилисский университет, психология",
    webSite: "https://kovalenko-recruiter.ge",
    occupation: "HR",
    interests: "Психология, чтение, искусство",
    phoneNumber: "+7 900 123 45 67",
    email: "kovalenko.alexandra@mail.ge",
    socialMedia: {
      instagram: "@alexandra_recruiter",
      twitter: "@kovalenko_a",
      linkedin: "linkedin.com/in/alexandra-kovalenko",
    },
    statusText: "Онлайн",
  },
  {
    id: 29,
    status: false,
    name: "Юлия Кузнецова",
    // title: "SEO-специалист",
    avatar: "https://i.ibb.co/8bGXZHz/user-avatar-29.jpg",
    location: { country: "Узбекистан", city: "Ташкент" },
    dateOfBirth: "1992-05-17",
    education: "Ташкентский университет, информатика",
    webSite: "https://kuznetsova-seo.uz",
    occupation: "SEO",
    interests: "SEO, блогинг, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "kuznetsova.yulia@mail.uz",
    socialMedia: {
      instagram: "@yulia_seo",
      twitter: "@kuznetsova_y",
      linkedin: "linkedin.com/in/yulia-kuznetsova",
    },
    statusText: "Не в сети",
  },
  {
    id: 30,
    status: true,
    name: "Мария Чернова",
    // title: "Журналист",
    avatar: "https://i.ibb.co/mFtbw7q/user-avatar-30.jpg",
    location: { country: "Франция", city: "Париж" },
    dateOfBirth: "1989-12-05",
    education: "Парижский университет, журналистика",
    webSite: "https://chernova-journalist.fr",
    occupation: "Медиа-компания",
    interests: "Журналистика, культура, социальные сети",
    phoneNumber: "+7 900 123 45 67",
    email: "chernova.maria@mail.fr",
    socialMedia: {
      instagram: "@maria_journalist",
      twitter: "@chernova_m",
      linkedin: "linkedin.com/in/maria-chernova",
    },
    statusText: "Онлайн",
  },
  {
    id: 31,
    status: false,
    name: "Екатерина Иванова",
    // title: "Маркетолог",
    avatar: "https://i.ibb.co/svQgCtX/user-avatar-31.jpg",
    location: { country: "Казахстан", city: "Астана" },
    dateOfBirth: "1991-07-19",
    education: "КазНУ, маркетинг",
    webSite: "https://ivanova-marketing.kz",
    occupation: "Маркетинг",
    interests: "Стратегия, спорт, кино",
    phoneNumber: "+7 900 123 45 67",
    email: "ivanova.katya@mail.kz",
    socialMedia: {
      instagram: "@katya_marketing",
      twitter: "@ivanova_k",
      linkedin: "linkedin.com/in/katya-ivanova",
    },
    statusText: "Не в сети",
  },
  {
    id: 32,
    status: true,
    name: "Петр Федоров",
    // title: "Программист",
    avatar: "https://i.ibb.co/8c47XKq/user-avatar-32.jpg",
    location: { country: "Таджикистан", city: "Душанбе" },
    dateOfBirth: "1994-01-28",
    education: "Таджикский университет, IT",
    webSite: "https://fedorov-dev.tj",
    occupation: "Фриланс",
    interests: "Программирование, музыка, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "fedorov.peter@mail.tj",
    socialMedia: {
      instagram: "@peter_dev",
      twitter: "@fedorov_p",
      linkedin: "linkedin.com/in/peter-fedorov",
    },
    statusText: "Онлайн",
  },
  {
    id: 33,
    status: false,
    name: "Светлана Шевченко",
    // title: "Дизайнер",
    avatar: "https://i.ibb.co/K9bgnPq/user-avatar-33.jpg",
    location: { country: "Молдавия", city: "Кишинев" },
    dateOfBirth: "1990-05-03",
    education: "Кишиневский университет, искусство",
    webSite: "https://shevchenko-design.md",
    occupation: "Графический дизайнер",
    interests: "Дизайн, культура, живопись",
    phoneNumber: "+7 900 123 45 67",
    email: "shevchenko.svetlana@mail.md",
    socialMedia: {
      instagram: "@svetlana_design",
      twitter: "@shevchenko_s",
      linkedin: "linkedin.com/in/svetlana-shevchenko",
    },
    statusText: "Не в сети",
  },
  {
    id: 34,
    status: true,
    name: "Владимир Кузнецов",
    // title: "Веб-разработчик",
    avatar: "https://i.ibb.co/nQDqcGZ/user-avatar-34.jpg",
    location: { country: "Латвия", city: "Рига" },
    dateOfBirth: "1993-03-15",
    education: "Рижская школа бизнеса, информатика",
    webSite: "https://kuznetsov-web.lv",
    occupation: "Веб-разработка",
    interests: "Технологии, стартапы, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "kuznetsov.vlad@mail.lv",
    socialMedia: {
      instagram: "@vlad_web",
      twitter: "@kuznetsov_v",
      linkedin: "linkedin.com/in/vlad-kuznetsov",
    },
    statusText: "Онлайн",
  },
  {
    id: 35,
    status: false,
    name: "Андрей Романов",
    // title: "Системный администратор",
    avatar: "https://i.ibb.co/82rY2vW/user-avatar-35.jpg",
    location: { country: "Азербайджан", city: "Баку" },
    dateOfBirth: "1988-09-10",
    education: "Азербайджанский университет, IT",
    webSite: "https://romanov-admin.az",
    occupation: "IT",
    interests: "Сетевые технологии, кино, спорт",
    phoneNumber: "+7 900 123 45 67",
    email: "romanov.andrey@mail.az",
    socialMedia: {
      instagram: "@andrey_admin",
      twitter: "@romanov_a",
      linkedin: "linkedin.com/in/andrey-romanov",
    },
    statusText: "Не в сети",
  },
  {
    id: 36,
    status: true,
    name: "Ирина Соколова",
    // title: "SEO-специалист",
    avatar: "https://i.ibb.co/gvqQbrZ/user-avatar-36.jpg",
    location: { country: "Армения", city: "Ереван" },
    dateOfBirth: "1995-11-30",
    education: "Ереванский университет, маркетинг",
    webSite: "https://sokolova-seo.am",
    occupation: "SEO",
    interests: "SEO, социальные сети, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "sokolova.irina@mail.am",
    socialMedia: {
      instagram: "@irina_seo",
      twitter: "@sokolova_i",
      linkedin: "linkedin.com/in/irina-sokolova",
    },
    statusText: "Онлайн",
  },
  {
    id: 37,
    status: false,
    name: "Мария Лебедева",
    // title: "Бухгалтер",
    avatar: "https://i.ibb.co/cNQHdkw/user-avatar-37.jpg",
    location: { country: "Киргизия", city: "Бишкек" },
    dateOfBirth: "1992-07-17",
    education: "Бишкекский университет, экономика",
    webSite: "https://lebedeva-accounting.kg",
    occupation: "Бухгалтерия",
    interests: "Финансы, книги, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "lebedeva.maria@mail.kg",
    socialMedia: {
      instagram: "@maria_accounting",
      twitter: "@lebedeva_m",
      linkedin: "linkedin.com/in/maria-lebedeva",
    },
    statusText: "Не в сети",
  },
  {
    id: 38,
    status: true,
    name: "Роман Воронов",
    // title: "Рекрутер",
    avatar: "https://i.ibb.co/GFnxcHZ/user-avatar-38.jpg",
    location: { country: "Молдова", city: "Кишинев" },
    dateOfBirth: "1990-06-25",
    education: "Кишиневский университет, психология",
    webSite: "https://voronov-recruiter.md",
    occupation: "HR",
    interests: "Психология, подбор персонала",
    phoneNumber: "+7 900 123 45 67",
    email: "voronov.roman@mail.md",
    socialMedia: {
      instagram: "@roman_recruiter",
      twitter: "@voronov_r",
      linkedin: "linkedin.com/in/roman-voronov",
    },
    statusText: "Онлайн",
  },
  {
    id: 39,
    status: false,
    name: "Оксана Павлова",
    // title: "HR-менеджер",
    avatar: "https://i.ibb.co/cQwNG1R/user-avatar-39.jpg",
    location: { country: "Узбекистан", city: "Ташкент" },
    dateOfBirth: "1987-02-22",
    education: "Ташкентский университет, психология",
    webSite: "https://pavlova-hr.uz",
    occupation: "HR",
    interests: "Психология, путешествия, спорт",
    phoneNumber: "+7 900 123 45 67",
    email: "pavlova.oksana@mail.uz",
    socialMedia: {
      instagram: "@oksana_hr",
      twitter: "@pavlova_o",
      linkedin: "linkedin.com/in/oksana-pavlova",
    },
    statusText: "Не в сети",
  },
  {
    id: 40,
    status: true,
    name: "Сергей Васильев",
    // title: "Маркетолог",
    avatar: "https://i.ibb.co/fDKJSww/user-avatar-40.jpg",
    location: { country: "Грузия", city: "Тбилиси" },
    dateOfBirth: "1991-12-11",
    education: "Тбилисский университет, маркетинг",
    webSite: "https://vasiliev-marketing.ge",
    occupation: "Маркетинг",
    interests: "Брендинг, социальные сети, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "vasiliev.sergey@mail.ge",
    socialMedia: {
      instagram: "@sergey_marketing",
      twitter: "@vasiliev_s",
      linkedin: "linkedin.com/in/sergey-vasiliev",
    },
    statusText: "Онлайн",
  },
  {
    id: 41,
    status: false,
    name: "Иван Иванов",
    // title: "Младший разработчик",
    avatar: "https://i.ibb.co/PFKYdGK/user-avatar-41.jpg",
    location: { country: "Россия", city: "Москва" },
    dateOfBirth: "1995-03-10",
    education: "МГУ, Факультет компьютерных наук",
    webSite: "https://ivan-ivanov.dev",
    occupation: "Программист",
    interests: "Игры, программирование, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "ivan.ivanov@email.com",
    socialMedia: {
      instagram: "@ivan_dev",
      twitter: "@ivan_dev",
      linkedin: "linkedin.com/in/ivan-ivanov",
    },
    statusText: "В поиске новых возможностей",
  },
  {
    id: 42,
    status: true,
    name: "Мария Смирнова",
    // title: "Дизайнер UI/UX",
    avatar: "https://i.ibb.co/hYdhN34/user-avatar-42.jpg",
    location: { country: "Россия", city: "Санкт-Петербург" },
    dateOfBirth: "1990-07-22",
    education: "СПбГУ, Факультет дизайна",
    webSite: "https://maria-design.com",
    occupation: "UI/UX дизайнер",
    interests: "Графический дизайн, фотография, кулинария",
    phoneNumber: "+7 900 987 65 43",
    email: "maria.smirnova@email.com",
    socialMedia: {
      instagram: "@maria_design",
      twitter: "@maria_design",
      linkedin: "linkedin.com/in/maria-smirnova",
    },
    statusText: "Работаю над новыми проектами",
  },
  {
    id: 43,
    status: false,
    name: "Алексей Петров",
    // title: "Аналитик данных",
    avatar: "https://i.ibb.co/ws57vyR/user-avatar-43.jpg",
    location: { country: "Россия", city: "Новосибирск" },
    dateOfBirth: "1988-11-15",
    education: "НИУ ВШЭ, Экономика и анализ данных",
    webSite: "https://alexey-data.com",
    occupation: "Аналитик данных",
    interests: "Большие данные, машинное обучение, музыка",
    phoneNumber: "+7 900 234 56 78",
    email: "alexey.petrov@email.com",
    socialMedia: {
      instagram: "@alexey_data",
      twitter: "@alexey_data",
      linkedin: "linkedin.com/in/alexey-petrov",
    },
    statusText: "Изучаю новые технологии анализа данных",
  },
  {
    id: 44,
    status: true,
    name: "Ольга Васильева",
    // title: "Маркетолог",
    avatar: "https://i.ibb.co/nP4GRgS/user-avatar-44.jpg",
    location: { country: "Россия", city: "Казань" },
    dateOfBirth: "1992-04-30",
    education: "КФУ, Маркетинг",
    webSite: "https://olga-marketing.com",
    occupation: "Маркетолог",
    interests: "Цифровой маркетинг, стартапы, путешествия",
    phoneNumber: "+7 900 345 67 89",
    email: "olga.vasilieva@email.com",
    socialMedia: {
      instagram: "@olga_marketing",
      twitter: "@olga_marketing",
      linkedin: "linkedin.com/in/olga-vasilieva",
    },
    statusText: "Разрабатываю новые маркетинговые стратегии",
  },
  {
    id: 45,
    status: false,
    name: "Дмитрий Козлов",
    // title: "Менеджер проектов",
    avatar: "https://i.ibb.co/nPp9NYs/user-avatar-45.jpg",
    location: { country: "Россия", city: "Екатеринбург" },
    dateOfBirth: "1985-09-05",
    education: "УрГЭУ, Менеджмент",
    webSite: "https://dmitry-projects.com",
    occupation: "Менеджер проектов",
    interests: "Управление проектами, бизнес, спорт",
    phoneNumber: "+7 900 456 78 90",
    email: "dmitry.kozlov@email.com",
    socialMedia: {
      instagram: "@dmitry_projects",
      twitter: "@dmitry_projects",
      linkedin: "linkedin.com/in/dmitry-kozlov",
    },
    statusText: "Завершаю текущие проекты",
  },
  {
    id: 46,
    status: true,
    name: "Анастасия Романова",
    // title: "Руководитель отдела продаж",
    avatar: "https://i.ibb.co/MSz9QTL/user-avatar-46.jpg",
    location: { country: "Россия", city: "Красноярск" },
    dateOfBirth: "1994-01-10",
    education: "КРИТ, Бизнес-администрирование",
    webSite: "https://anastasia-sales.com",
    occupation: "Руководитель отдела продаж",
    interests: "Продажи, психология, саморазвитие",
    phoneNumber: "+7 900 567 89 01",
    email: "anastasia.romanova@email.com",
    socialMedia: {
      instagram: "@anastasia_sales",
      twitter: "@anastasia_sales",
      linkedin: "linkedin.com/in/anastasia-romanova",
    },
    statusText: "Открыта для новых возможностей",
  },
  {
    id: 47,
    status: false,
    name: "Максим Орлов",
    // title: "Системный администратор",
    avatar: "https://i.ibb.co/P9Q6FKd/user-avatar-47.jpg",
    location: { country: "Россия", city: "Пермь" },
    dateOfBirth: "1989-12-25",
    education:
      "Пермский государственный университет, Информационные технологии",
    webSite: "https://maxim-it.com",
    occupation: "Системный администратор",
    interests: "Сетевые технологии, кибербезопасность, автомобили",
    phoneNumber: "+7 900 678 90 12",
    email: "maxim.orlov@email.com",
    socialMedia: {
      instagram: "@maxim_it",
      twitter: "@maxim_it",
      linkedin: "linkedin.com/in/maxim-orlov",
    },
    statusText: "Работаю над системной инфраструктурой",
  },
  {
    id: 48,
    status: true,
    name: "Елена Белова",
    // title: "Арт-директор",
    avatar: "https://i.ibb.co/By7PHCZ/user-avatar-48.jpg",
    location: { country: "Россия", city: "Сочи" },
    dateOfBirth: "1991-02-18",
    education: "ЮФУ, Дизайн",
    webSite: "https://elena-art.com",
    occupation: "Арт-директор",
    interests: "Искусство, графический дизайн, мода",
    phoneNumber: "+7 900 789 01 23",
    email: "elena.belova@email.com",
    socialMedia: {
      instagram: "@elena_art",
      twitter: "@elena_art",
      linkedin: "linkedin.com/in/elena-belova",
    },
    statusText: "Творю и ищу вдохновение",
  },
  {
    id: 49,
    status: false,
    name: "Юрий Ковалев",
    // title: "Frontend-разработчик",
    avatar: "https://i.ibb.co/4Z77nKD/user-avatar-49.jpg",
    location: { country: "Россия", city: "Уфа" },
    dateOfBirth: "1996-06-09",
    education: "Башкирский государственный университет, Программирование",
    webSite: "https://yuri-front.com",
    occupation: "Frontend-разработчик",
    interests: "Веб-разработка, JavaScript, спорт",
    phoneNumber: "+7 900 890 12 34",
    email: "yuri.kovalev@email.com",
    socialMedia: {
      instagram: "@yuri_front",
      twitter: "@yuri_front",
      linkedin: "linkedin.com/in/yuri-kovalev",
    },
    statusText: "Работаю над новыми проектами",
  },
  {
    id: 50,
    status: true,
    name: "Светлана Климова",
    // title: "HR-менеджер",
    avatar: "https://i.ibb.co/HtHkN3T/user-avatar-50.jpg",
    location: { country: "Россия", city: "Владивосток" },
    dateOfBirth: "1987-05-12",
    education: "Дальневосточный федеральный университет, Управление персоналом",
    webSite: "https://svetlana-hr.com",
    occupation: "HR-менеджер",
    interests: "Рекрутинг, психология, театр",
    phoneNumber: "+7 900 901 23 45",
    email: "svetlana.klimova@email.com",
    socialMedia: {
      instagram: "@svetlana_hr",
      twitter: "@svetlana_hr",
      linkedin: "linkedin.com/in/svetlana-klimova",
    },
    statusText: "Ищу таланты для новых проектов",
  },
  {
    id: 51,
    status: false,
    name: "Кирилл Николаев",
    // title: "Frontend-разработчик",
    avatar: "https://i.ibb.co/9Gm3PLM/user-avatar-01.jpg",
    location: { country: "Россия", city: "Томск" },
    dateOfBirth: "1994-03-02",
    education: "Томский государственный университет, Программирование",
    webSite: "https://kirill-frontend.com",
    occupation: "Frontend-разработчик",
    interests: "Веб-разработка, JavaScript, кино",
    phoneNumber: "+7 900 123 45 67",
    email: "kirill.nikolaev@email.com",
    socialMedia: {
      instagram: "@kirill_front",
      twitter: "@kirill_front",
      linkedin: "linkedin.com/in/kirill-nikolaev",
    },
    statusText: "Работаю над новыми веб-проектами",
  },
  {
    id: 52,
    status: true,
    name: "Екатерина Попова",
    // title: "SEO-специалист",
    avatar: "https://i.ibb.co/6JN2kcJ/user-avatar-02.jpg",
    location: { country: "Россия", city: "Воронеж" },
    dateOfBirth: "1990-08-14",
    education: "Воронежский государственный университет, Маркетинг",
    webSite: "https://katya-seo.com",
    occupation: "SEO-специалист",
    interests: "SEO, интернет-маркетинг, музыка",
    phoneNumber: "+7 900 123 45 67",
    email: "ekaterina.popova@email.com",
    socialMedia: {
      instagram: "@katya_seo",
      twitter: "@katya_seo",
      linkedin: "linkedin.com/in/ekaterina-popova",
    },
    statusText: "Помогаю сайтам быть видимыми",
  },
  {
    id: 53,
    status: false,
    name: "Дмитрий Сидоров",
    // title: "Веб-дизайнер",
    avatar: "https://i.ibb.co/tb8qRNc/user-avatar-03.jpg",
    location: { country: "Россия", city: "Челябинск" },
    dateOfBirth: "1992-01-28",
    education: "ЮУрГУ, Дизайн",
    webSite: "https://dmitry-design.com",
    occupation: "Веб-дизайнер",
    interests: "Дизайн интерфейсов, фотографии, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "dmitry.sidorov@email.com",
    socialMedia: {
      instagram: "@dmitry_design",
      twitter: "@dmitry_design",
      linkedin: "linkedin.com/in/dmitry-sidorov",
    },
    statusText: "Творю красивые и удобные сайты",
  },
  {
    id: 54,
    status: true,
    name: "Ирина Васильева",
    // title: "Менеджер по продуктам",
    avatar: "https://i.ibb.co/sPSJfd3/user-avatar-04.jpg",
    location: { country: "Россия", city: "Ростов-на-Дону" },
    dateOfBirth: "1993-09-11",
    education: "Ростовский государственный университет, Менеджмент",
    webSite: "https://irina-products.com",
    occupation: "Менеджер по продуктам",
    interests: "Продуктовый менеджмент, технологии, спорт",
    phoneNumber: "+7 900 123 45 67",
    email: "irina.vasileva@email.com",
    socialMedia: {
      instagram: "@irina_product",
      twitter: "@irina_product",
      linkedin: "linkedin.com/in/irina-vasileva",
    },
    statusText: "Разрабатываю новые продукты",
  },
  {
    id: 55,
    status: false,
    name: "Владимир Петров",
    // title: "Разработчик Python",
    avatar: "https://i.ibb.co/TKY9qTW/user-avatar-05.jpg",
    location: { country: "Россия", city: "Ульяновск" },
    dateOfBirth: "1994-05-18",
    education:
      "Ульяновский государственный технический университет, Программирование",
    webSite: "https://vladimir-python.com",
    occupation: "Разработчик Python",
    interests: "Программирование, искусственный интеллект, шахматы",
    phoneNumber: "+7 900 123 45 67",
    email: "vladimir.petrov@email.com",
    socialMedia: {
      instagram: "@vladimir_python",
      twitter: "@vladimir_python",
      linkedin: "linkedin.com/in/vladimir-petrov",
    },
    statusText: "Изучаю новые возможности в Python",
  },
  {
    id: 56,
    status: true,
    name: "Светлана Иванова",
    // title: "Data Scientist",
    avatar: "https://i.ibb.co/3MHMXV6/user-avatar-06.jpg",
    location: { country: "Россия", city: "Петрозаводск" },
    dateOfBirth: "1989-04-02",
    education: "Петрозаводский университет, Математика и статистика",
    webSite: "https://svetlana-datascience.com",
    occupation: "Data Scientist",
    interests: "Анализ данных, машинное обучение, литература",
    phoneNumber: "+7 900 123 45 67",
    email: "svetlana.ivanova@email.com",
    socialMedia: {
      instagram: "@svetlana_data",
      twitter: "@svetlana_data",
      linkedin: "linkedin.com/in/svetlana-ivanova",
    },
    statusText: "Использую данные для улучшения процессов",
  },
  {
    id: 57,
    status: false,
    name: "Роман Громов",
    // title: "Инженер DevOps",
    avatar: "https://i.ibb.co/p3fmNrV/user-avatar-07.jpg",
    location: { country: "Россия", city: "Тула" },
    dateOfBirth: "1991-12-03",
    education:
      "Тульский государственный университет, Информационные технологии",
    webSite: "https://roman-devops.com",
    occupation: "Инженер DevOps",
    interests: "Автоматизация процессов, кибербезопасность, музыка",
    phoneNumber: "+7 900 123 45 67",
    email: "roman.gromov@email.com",
    socialMedia: {
      instagram: "@roman_devops",
      twitter: "@roman_devops",
      linkedin: "linkedin.com/in/roman-gromov",
    },
    statusText: "Работаю над автоматизацией DevOps процессов",
  },
  {
    id: 58,
    status: true,
    name: "Александра Кузнецова",
    // title: "PR-менеджер",
    avatar: "https://i.ibb.co/KG9RhWQ/user-avatar-08.jpg",
    location: { country: "Россия", city: "Смоленск" },
    dateOfBirth: "1988-11-30",
    education: "Смоленский государственный университет, Журналистика",
    webSite: "https://alexandra-pr.com",
    occupation: "PR-менеджер",
    interests: "Публичные выступления, маркетинг, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "alexandra.kuznetsova@email.com",
    socialMedia: {
      instagram: "@alexandra_pr",
      twitter: "@alexandra_pr",
      linkedin: "linkedin.com/in/alexandra-kuznetsova",
    },
    statusText: "Планирую PR-кампании для новых брендов",
  },
  {
    id: 59,
    status: false,
    name: "Никита Борисов",
    // title: "Администратор баз данных",
    avatar: "https://i.ibb.co/hBx5TH9/user-avatar-09.jpg",
    location: { country: "Россия", city: "Саратов" },
    dateOfBirth: "1990-06-17",
    education: "Саратовский государственный университет, Базы данных",
    webSite: "https://nikita-db.com",
    occupation: "Администратор баз данных",
    interests: "Базы данных, оптимизация, спорт",
    phoneNumber: "+7 900 123 45 67",
    email: "nikita.borisov@email.com",
    socialMedia: {
      instagram: "@nikita_db",
      twitter: "@nikita_db",
      linkedin: "linkedin.com/in/nikita-borisov",
    },
    statusText: "Оптимизирую базы данных для улучшения производительности",
  },
  {
    id: 60,
    status: true,
    name: "Марина Павлова",
    // title: "HR-специалист",
    avatar: "https://i.ibb.co/FVqnf9M/user-avatar-10.jpg",
    location: { country: "Россия", city: "Астрахань" },
    dateOfBirth: "1992-05-21",
    education:
      "Астраханский государственный университет, Управление персоналом",
    webSite: "https://marina-hr.com",
    occupation: "HR-специалист",
    interests: "Рекрутинг, психология, волонтёрство",
    phoneNumber: "+7 900 123 45 67",
    email: "marina.pavlova@email.com",
    socialMedia: {
      instagram: "@marina_hr",
      twitter: "@marina_hr",
      linkedin: "linkedin.com/in/marina-pavlova",
    },
    statusText: "Помогаю находить лучших сотрудников",
  },
  {
    id: 61,
    status: false,
    name: "Анатолий Смирнов",
    // title: "Full-stack разработчик",
    avatar: "https://i.ibb.co/SVhHhtN/user-avatar-11.jpg",
    location: { country: "Россия", city: "Калуга" },
    dateOfBirth: "1995-04-23",
    education:
      "Калужский государственный университет, Информационные технологии",
    webSite: "https://anatoly-fullstack.com",
    occupation: "Full-stack разработчик",
    interests: "JavaScript, React, Python, музыка",
    phoneNumber: "+7 900 123 45 67",
    email: "anatoly.smirnov@email.com",
    socialMedia: {
      instagram: "@anatoly_dev",
      twitter: "@anatoly_dev",
      linkedin: "linkedin.com/in/anatoly-smirnov",
    },
    statusText: "Работаю над новыми фичами для приложений",
  },
  {
    id: 62,
    status: true,
    name: "Ирина Белова",
    // title: "Маркетолог",
    avatar: "https://i.ibb.co/dfrG1nM/user-avatar-12.jpg",
    location: { country: "Россия", city: "Новосибирск" },
    dateOfBirth: "1992-06-05",
    education: "Новосибирский государственный университет, Маркетинг",
    webSite: "https://irina-marketing.com",
    occupation: "Маркетолог",
    interests: "Интернет-маркетинг, контент-менеджмент, путешествия",
    phoneNumber: "+7 900 123 45 67",
    email: "irina.belova@email.com",
    socialMedia: {
      instagram: "@irina_marketing",
      twitter: "@irina_marketing",
      linkedin: "linkedin.com/in/irina-belova",
    },
    statusText: "Планирую успешные маркетинговые кампании",
  },
  {
    id: 63,
    status: false,
    name: "Олег Федоров",
    // // title: "Android-разработчик",
    avatar: "https://i.ibb.co/48d19pW/user-avatar-13.jpg",
    location: { country: "Россия", city: "Тверь" },
    dateOfBirth: "1993-11-10",
    education: "Тверской государственный университет, Программирование",
    webSite: "https://oleg-android.com",
    occupation: "Android-разработчик",
    interests: "Android, Kotlin, мобильные приложения",
    phoneNumber: "+7 900 123 45 67",
    email: "oleg.fedorov@email.com",
    socialMedia: {
      instagram: "@oleg_android",
      twitter: "@oleg_android",
      linkedin: "linkedin.com/in/oleg-fedorov",
    },
    statusText: "Разрабатываю удобные мобильные приложения",
  },
  {
    id: 64,
    status: true,
    name: "Владислав Титов",
    // // title: "UI/UX дизайнер",
    avatar: "https://i.ibb.co/MnF8gTN/user-avatar-14.jpg",
    location: { country: "Россия", city: "Екатеринбург" },
    dateOfBirth: "1989-03-22",
    education: "Уральский федеральный университет, Дизайн интерфейсов",
    webSite: "https://vladislav-design.com",
    occupation: "UI/UX дизайнер",
    interests: "Дизайн, улучшение пользовательского опыта, графика",
    phoneNumber: "+7 900 123 45 67",
    email: "vladislav.titov@email.com",
    socialMedia: {
      instagram: "@vladislav_design",
      twitter: "@vladislav_design",
      linkedin: "linkedin.com/in/vladislav-titov",
    },
    statusText: "Создаю интерфейсы, которые делают пользователей счастливыми",
  },
  {
    id: 65,
    status: false,
    name: "Роман Дорофеев",
    // // title: "Разработчик C++",
    avatar: "https://i.ibb.co/9rBjyYZ/user-avatar-15.jpg",
    location: { country: "Россия", city: "Мурманск" },
    dateOfBirth: "1996-02-13",
    education:
      "Мурманский арктический государственный университет, Программирование",
    webSite: "https://roman-cpp.com",
    occupation: "Разработчик C++",
    interests: "Программирование, алгоритмы, встраиваемые системы",
    phoneNumber: "+7 900 123 45 67",
    email: "roman.dorofeev@email.com",
    socialMedia: {
      instagram: "@roman_cpp",
      twitter: "@roman_cpp",
      linkedin: "linkedin.com/in/roman-dorofeev",
    },
    statusText: "Работаю над улучшением производительности программ",
  },
  {
    id: 66,
    status: true,
    name: "Светлана Кузнецова",
    // // title: "Проект-менеджер",
    avatar: "https://i.ibb.co/zn2rcMM/user-avatar-16.jpg",
    location: { country: "Россия", city: "Волгоград" },
    dateOfBirth: "1988-07-19",
    education:
      "Волгоградский государственный университет, Управление проектами",
    webSite: "https://svetlana-project.com",
    occupation: "Проект-менеджер",
    interests: "Управление проектами, лидерство, фитнес",
    phoneNumber: "+7 900 123 45 67",
    email: "svetlana.kuznetsova@email.com",
    socialMedia: {
      instagram: "@svetlana_project",
      twitter: "@svetlana_project",
      linkedin: "linkedin.com/in/svetlana-kuznetsova",
    },
    statusText: "Руководствую проектами для достижения целей",
  },
  {
    id: 67,
    status: false,
    name: "Виктория Николаева",
    // // title: "Тестировщик ПО",
    avatar: "https://i.ibb.co/CMcwwkm/user-avatar-17.jpg",
    location: { country: "Россия", city: "Кострома" },
    dateOfBirth: "1994-09-09",
    education: "Костромской государственный университет, Информатика",
    webSite: "https://victoria-testing.com",
    occupation: "Тестировщик ПО",
    interests: "Тестирование, улучшение качества ПО, книги",
    phoneNumber: "+7 900 123 45 67",
    email: "victoria.nikolaeva@email.com",
    socialMedia: {
      instagram: "@victoria_testing",
      twitter: "@victoria_testing",
      linkedin: "linkedin.com/in/victoria-nikolaeva",
    },
    statusText: "Тестирую ПО и ищу баги",
  },
  {
    id: 68,
    status: true,
    name: "Григорий Лебедев",
    // // title: "Системный администратор",
    avatar: "https://i.ibb.co/VTJs5Rx/user-avatar-18.jpg",
    location: { country: "Россия", city: "Ярославль" },
    dateOfBirth: "1991-05-17",
    education: "Ярославский государственный университет, Системы и сети",
    webSite: "https://grigory-sysadmin.com",
    occupation: "Системный администратор",
    interests: "Сетевые технологии, безопасность, Linux",
    phoneNumber: "+7 900 123 45 67",
    email: "grigory.lebedev@email.com",
    socialMedia: {
      instagram: "@grigory_sysadmin",
      twitter: "@grigory_sysadmin",
      linkedin: "linkedin.com/in/grigory-lebedev",
    },
    statusText: "Поддерживаю инфраструктуру и сетевые решения",
  },
  {
    id: 69,
    status: false,
    name: "Ксения Волкова",
    // // title: "DevOps-инженер",
    avatar: "https://i.ibb.co/WxpV5wN/user-avatar-19.jpg",
    location: { country: "Россия", city: "Сочи" },
    dateOfBirth: "1992-11-14",
    education: "Сочинский государственный университет, Инженерия",
    webSite: "https://ksenia-devops.com",
    occupation: "DevOps-инженер",
    interests: "Автоматизация, контейнеризация, Docker",
    phoneNumber: "+7 900 123 45 67",
    email: "ksenia.volkova@email.com",
    socialMedia: {
      instagram: "@ksenia_devops",
      twitter: "@ksenia_devops",
      linkedin: "linkedin.com/in/ksenia-volkova",
    },
    statusText: "Оптимизирую процессы и системы",
  },
  {
    id: 70,
    status: true,
    name: "Никита Павлов",
    // // title: "Технический писатель",
    avatar: "https://i.ibb.co/RDyF02W/user-avatar-20.jpg",
    location: { country: "Россия", city: "Владивосток" },
    dateOfBirth: "1987-10-02",
    education: "Дальневосточный федеральный университет, Лингвистика",
    webSite: "https://nikita-writer.com",
    occupation: "Технический писатель",
    interests: "Документация, написание технических материалов",
    phoneNumber: "+7 900 123 45 67",
    email: "nikita.pavlov@email.com",
    socialMedia: {
      instagram: "@nikita_writer",
      twitter: "@nikita_writer",
      linkedin: "linkedin.com/in/nikita-pavlov",
    },
    statusText: "Создаю понятные инструкции для пользователей",
  },
  {
    id: 71,
    status: false,
    name: "Марина Дмитриева",
    // // title: "UI дизайнер",
    avatar: "https://i.ibb.co/VSgYB4f/user-avatar-21.jpg",
    location: { country: "Россия", city: "Уфа" },
    dateOfBirth: "1990-02-17",
    education: "Башкирский государственный университет, Дизайн",
    webSite: "https://marina-uidesigner.com",
    occupation: "UI дизайнер",
    interests: "Графический дизайн, интерфейсы, музыка",
    phoneNumber: "+7 900 123 45 67",
    email: "marina.dmitrieva@email.com",
    socialMedia: {
      instagram: "@marina_design",
      twitter: "@marina_design",
      linkedin: "linkedin.com/in/marina-dmitrieva",
    },
    statusText: "Дизайн красивых и удобных интерфейсов",
  },
  {
    id: 72,
    status: true,
    name: "Денис Баранов",
    // // title: "Data Scientist",
    avatar: "https://i.ibb.co/2s2S33g/user-avatar-22.jpg",
    location: { country: "Россия", city: "Томск" },
    dateOfBirth: "1985-07-12",
    education: "Томский государственный университет, Математика",
    webSite: "https://denis-data.com",
    occupation: "Data Scientist",
    interests: "Машинное обучение, Python, большие данные",
    phoneNumber: "+7 900 123 45 67",
    email: "denis.baranov@email.com",
    socialMedia: {
      instagram: "@denis_data",
      twitter: "@denis_data",
      linkedin: "linkedin.com/in/denis-baranov",
    },
    statusText: "Работаю с большими данными и моделями",
  },
  {
    id: 73,
    status: false,
    name: "Иван Ребров",
    // // title: "Сетевой инженер",
    avatar: "https://i.ibb.co/vkC9Hct/user-avatar-23.jpg",
    location: { country: "Россия", city: "Казань" },
    dateOfBirth: "1994-11-25",
    education: "Казанский федеральный университет, Информационные технологии",
    webSite: "https://ivan-network.com",
    occupation: "Сетевой инженер",
    interests: "Сетевые технологии, безопасность",
    phoneNumber: "+7 900 123 45 67",
    email: "ivan.rebrov@email.com",
    socialMedia: {
      instagram: "@ivan_network",
      twitter: "@ivan_network",
      linkedin: "linkedin.com/in/ivan-rebrov",
    },
    statusText: "Работаю над созданием надежных сетей",
  },
  {
    id: 74,
    status: true,
    name: "Екатерина Попова",
    // // title: "Frontend разработчик",
    avatar: "https://i.ibb.co/C12jhLb/user-avatar-24.jpg",
    location: { country: "Россия", city: "Санкт-Петербург" },
    dateOfBirth: "1993-03-06",
    education:
      "Санкт-Петербургский политехнический университет, Программирование",
    webSite: "https://ekaterina-frontend.com",
    occupation: "Frontend разработчик",
    interests: "JavaScript, React, веб-разработка",
    phoneNumber: "+7 900 123 45 67",
    email: "ekaterina.popova@email.com",
    socialMedia: {
      instagram: "@ekaterina_frontend",
      twitter: "@ekaterina_frontend",
      linkedin: "linkedin.com/in/ekaterina-popova",
    },
    statusText: "Создаю динамичные и интуитивно понятные веб-приложения",
  },
  {
    id: 75,
    status: false,
    name: "Алексей Иванов",
    // // title: "Backend разработчик",
    avatar: "https://i.ibb.co/7tTscBF/user-avatar-25.jpg",
    location: { country: "Россия", city: "Рязань" },
    dateOfBirth: "1991-09-21",
    education: "Рязанский государственный университет, Программирование",
    webSite: "https://alexey-backend.com",
    occupation: "Backend разработчик",
    interests: "Серверные технологии, Python, базы данных",
    phoneNumber: "+7 900 123 45 67",
    email: "alexey.ivanov@email.com",
    socialMedia: {
      instagram: "@alexey_backend",
      twitter: "@alexey_backend",
      linkedin: "linkedin.com/in/alexey-ivanov",
    },
    statusText: "Разрабатываю эффективные серверные решения",
  },
  {
    id: 76,
    status: true,
    name: "Мария Семёнова",
    // // title: "HR-менеджер",
    avatar: "https://i.ibb.co/7JXKr9H/user-avatar-26.jpg",
    location: { country: "Россия", city: "Тула" },
    dateOfBirth: "1986-12-18",
    education: "Тульский государственный университет, Психология",
    webSite: "https://maria-hr.com",
    occupation: "HR-менеджер",
    interests: "Рекрутинг, психология, развитие персонала",
    phoneNumber: "+7 900 123 45 67",
    email: "maria.semenova@email.com",
    socialMedia: {
      instagram: "@maria_hr",
      twitter: "@maria_hr",
      linkedin: "linkedin.com/in/maria-semenova",
    },
    statusText: "Помогаю находить и развивать талантливых людей",
  },
  {
    id: 77,
    status: false,
    name: "Анатолий Орлов",
    // // title: "DevOps инженер",
    avatar: "https://i.ibb.co/vYkZwgD/user-avatar-27.jpg",
    location: { country: "Россия", city: "Пенза" },
    dateOfBirth: "1992-04-10",
    education: "Пензенский государственный университет, Информатика",
    webSite: "https://anatoly-devops.com",
    occupation: "DevOps инженер",
    interests: "Автоматизация, CI/CD, Linux",
    phoneNumber: "+7 900 123 45 67",
    email: "anatoly.orlov@email.com",
    socialMedia: {
      instagram: "@anatoly_devops",
      twitter: "@anatoly_devops",
      linkedin: "linkedin.com/in/anatoly-orlov",
    },
    statusText: "Автоматизирую процессы разработки и тестирования",
  },
  {
    id: 78,
    status: true,
    name: "Сергей Никитин",
    // // title: "Программист Python",
    avatar: "https://i.ibb.co/vsWT86v/user-avatar-28.jpg",
    location: { country: "Россия", city: "Калуга" },
    dateOfBirth: "1994-03-14",
    education: "Калужский государственный университет, Программирование",
    webSite: "https://sergey-python.com",
    occupation: "Программист Python",
    interests: "Python, искусственный интеллект, разработка ПО",
    phoneNumber: "+7 900 123 45 67",
    email: "sergey.nikitin@email.com",
    socialMedia: {
      instagram: "@sergey_python",
      twitter: "@sergey_python",
      linkedin: "linkedin.com/in/sergey-nikitin",
    },
    statusText: "Работаю с искусственным интеллектом и машинным обучением",
  },
  {
    id: 79,
    status: false,
    name: "Елена Петрова",
    // // title: "SEO специалист",
    avatar: "https://i.ibb.co/8bGXZHz/user-avatar-29.jpg",
    location: { country: "Россия", city: "Смоленск" },
    dateOfBirth: "1995-08-23",
    education: "Смоленский государственный университет, Маркетинг",
    webSite: "https://elena-seo.com",
    occupation: "SEO специалист",
    interests: "SEO, контент-маркетинг, аналитика",
    phoneNumber: "+7 900 123 45 67",
    email: "elena.petrova@email.com",
    socialMedia: {
      instagram: "@elena_seo",
      twitter: "@elena_seo",
      linkedin: "linkedin.com/in/elena-petrova",
    },
    statusText: "Помогаю сайтам становиться видимыми в поиске",
  },
  {
    id: 80,
    status: true,
    name: "Виктор Смирнов",
    // // title: "Менеджер по продажам",
    avatar: "https://i.ibb.co/mFtbw7q/user-avatar-30.jpg",
    location: { country: "Россия", city: "Владимир" },
    dateOfBirth: "1989-11-11",
    education: "Владимирский государственный университет, Экономика",
    webSite: "https://viktor-sales.com",
    occupation: "Менеджер по продажам",
    interests: "Продажи, бизнес-развитие, переговоры",
    phoneNumber: "+7 900 123 45 67",
    email: "viktor.smirnov@email.com",
    socialMedia: {
      instagram: "@viktor_sales",
      twitter: "@viktor_sales",
      linkedin: "linkedin.com/in/viktor-smirnov",
    },
    statusText: "Помогаю бизнесу расти через эффективные продажи",
  },
  {
    id: 81,
    status: false,
    name: "Татьяна Мельникова",
    // // title: "HR менеджер",
    avatar: "https://i.ibb.co/svQgCtX/user-avatar-31.jpg",
    location: { country: "Россия", city: "Краснодар" },
    dateOfBirth: "1991-06-15",
    education: "Краснодарский государственный университет, Менеджмент",
    webSite: "https://tatiana-hr.com",
    occupation: "HR менеджер",
    interests: "Подбор персонала, корпоративная культура",
    phoneNumber: "+7 900 123 45 67",
    email: "tatiana.melnikova@email.com",
    socialMedia: {
      instagram: "@tatiana_hr",
      twitter: "@tatiana_hr",
      linkedin: "linkedin.com/in/tatiana-melnikova",
    },
    statusText: "Построение эффективных команд",
  },
  {
    id: 82,
    status: true,
    name: "Владимир Яковлев",
    // // title: "Frontend разработчик",
    avatar: "https://i.ibb.co/8c47XKq/user-avatar-32.jpg",
    location: { country: "Россия", city: "Воронеж" },
    dateOfBirth: "1990-11-08",
    education: "Воронежский государственный университет, Программирование",
    webSite: "https://vladimir-frontend.com",
    occupation: "Frontend разработчик",
    interests: "HTML, CSS, JavaScript",
    phoneNumber: "+7 900 123 45 67",
    email: "vladimir.yakovlev@email.com",
    socialMedia: {
      instagram: "@vladimir_frontend",
      twitter: "@vladimir_frontend",
      linkedin: "linkedin.com/in/vladimir-yakovlev",
    },
    statusText: "Строю красивые и доступные веб-приложения",
  },
  {
    id: 83,
    status: false,
    name: "Ольга Соколова",
    // // title: "UI/UX дизайнер",
    avatar: "https://i.ibb.co/K9bgnPq/user-avatar-33.jpg",
    location: { country: "Россия", city: "Ярославль" },
    dateOfBirth: "1992-02-19",
    education: "Ярославский государственный университет, Дизайн",
    webSite: "https://olga-uxdesign.com",
    occupation: "UI/UX дизайнер",
    interests: "Дизайн интерфейсов, исследование пользователей",
    phoneNumber: "+7 900 123 45 67",
    email: "olga.sokolova@email.com",
    socialMedia: {
      instagram: "@olga_ux",
      twitter: "@olga_ux",
      linkedin: "linkedin.com/in/olga-sokolova",
    },
    statusText: "Создаю дизайн с учетом потребностей пользователей",
  },
  {
    id: 84,
    status: true,
    name: "Александр Романов",
    // // title: "Разработчик Python",
    avatar: "https://i.ibb.co/nQDqcGZ/user-avatar-34.jpg",
    location: { country: "Россия", city: "Новосибирск" },
    dateOfBirth: "1988-04-23",
    education: "Новосибирский государственный университет, Программирование",
    webSite: "https://alexander-python.com",
    occupation: "Разработчик Python",
    interests: "Python, Django, разработка серверных приложений",
    phoneNumber: "+7 900 123 45 67",
    email: "alexander.romanov@email.com",
    socialMedia: {
      instagram: "@alexander_python",
      twitter: "@alexander_python",
      linkedin: "linkedin.com/in/alexander-romanov",
    },
    statusText: "Разрабатываю эффективные и масштабируемые приложения",
  },
  {
    id: 85,
    status: false,
    name: "Марина Козлова",
    // // title: "Менеджер по маркетингу",
    avatar: "https://i.ibb.co/82rY2vW/user-avatar-35.jpg",
    location: { country: "Россия", city: "Тверь" },
    dateOfBirth: "1993-09-17",
    education: "Тверской государственный университет, Маркетинг",
    webSite: "https://marina-marketing.com",
    occupation: "Менеджер по маркетингу",
    interests: "Маркетинговые стратегии, аналитика",
    phoneNumber: "+7 900 123 45 67",
    email: "marina.kozlova@email.com",
    socialMedia: {
      instagram: "@marina_marketing",
      twitter: "@marina_marketing",
      linkedin: "linkedin.com/in/marina-kozlova",
    },
    statusText: "Помогаю создавать маркетинговые стратегии для бизнеса",
  },
  {
    id: 86,
    status: true,
    name: "Дмитрий Попов",
    // // title: "Frontend разработчик",
    avatar: "https://i.ibb.co/gvqQbrZ/user-avatar-36.jpg",
    location: { country: "Россия", city: "Мурманск" },
    dateOfBirth: "1990-01-14",
    education: "Мурманский арктический университет, Программирование",
    webSite: "https://dmitry-frontend.com",
    occupation: "Frontend разработчик",
    interests: "React, HTML5, CSS3",
    phoneNumber: "+7 900 123 45 67",
    email: "dmitry.popov@email.com",
    socialMedia: {
      instagram: "@dmitry_frontend",
      twitter: "@dmitry_frontend",
      linkedin: "linkedin.com/in/dmitry-popov",
    },
    statusText: "Создаю современные веб-интерфейсы",
  },
  {
    id: 87,
    status: false,
    name: "Юлия Смирнова",
    // // title: "SEO специалист",
    avatar: "https://i.ibb.co/cNQHdkw/user-avatar-37.jpg",
    location: { country: "Россия", city: "Псков" },
    dateOfBirth: "1994-12-03",
    education: "Псковский государственный университет, Маркетинг",
    webSite: "https://julia-seo.com",
    occupation: "SEO специалист",
    interests: "SEO, контент-маркетинг, аналитика",
    phoneNumber: "+7 900 123 45 67",
    email: "julia.smirnova@email.com",
    socialMedia: {
      instagram: "@julia_seo",
      twitter: "@julia_seo",
      linkedin: "linkedin.com/in/julia-smirnova",
    },
    statusText: "Помогаю сайтам стать более видимыми в поиске",
  },
  {
    id: 88,
    status: true,
    name: "Алексей Викторов",
    // // title: "Менеджер по продажам",
    avatar: "https://i.ibb.co/GFnxcHZ/user-avatar-38.jpg",
    location: { country: "Россия", city: "Тула" },
    dateOfBirth: "1987-07-26",
    education: "Тульский государственный университет, Экономика",
    webSite: "https://alexey-sales.com",
    occupation: "Менеджер по продажам",
    interests: "Продажи, ведение переговоров, бизнес",
    phoneNumber: "+7 900 123 45 67",
    email: "alexey.viktorov@email.com",
    socialMedia: {
      instagram: "@alexey_sales",
      twitter: "@alexey_sales",
      linkedin: "linkedin.com/in/alexey-viktorov",
    },
    statusText: "Решения для успешных продаж и бизнеса",
  },
  {
    id: 89,
    status: false,
    name: "Никита Григорьев",
    // // title: "Системный администратор",
    avatar: "https://i.ibb.co/cQwNG1R/user-avatar-39.jpg",
    location: { country: "Россия", city: "Астрахань" },
    dateOfBirth: "1995-04-17",
    education:
      "Астраханский государственный университет, Информационные технологии",
    webSite: "https://nikita-sysadmin.com",
    occupation: "Системный администратор",
    interests: "Сетевые технологии, администрирование серверов",
    phoneNumber: "+7 900 123 45 67",
    email: "nikita.grigoryev@email.com",
    socialMedia: {
      instagram: "@nikita_sysadmin",
      twitter: "@nikita_sysadmin",
      linkedin: "linkedin.com/in/nikita-grigoryev",
    },
    statusText: "Поддержка и оптимизация IT инфраструктуры",
  },
  {
    id: 90,
    status: true,
    name: "Ирина Захарова",
    // // title: "Контент-менеджер",
    avatar: "https://i.ibb.co/fDKJSww/user-avatar-40.jpg",
    location: { country: "Россия", city: "Ростов-на-Дону" },
    dateOfBirth: "1992-10-08",
    education: "Ростовский государственный университет, Журналистика",
    webSite: "https://irina-content.com",
    occupation: "Контент-менеджер",
    interests: "Контент-маркетинг, копирайтинг",
    phoneNumber: "+7 900 123 45 67",
    email: "irina.zakharova@email.com",
    socialMedia: {
      instagram: "@irina_content",
      twitter: "@irina_content",
      linkedin: "linkedin.com/in/irina-zakharova",
    },
    statusText: "Создаю качественный контент для бизнеса",
  },
  {
    id: 91,
    status: false,
    name: "Виктория Лебедева",
    // // title: "UX-исследователь",
    avatar: "https://i.ibb.co/PFKYdGK/user-avatar-41.jpg",
    location: { country: "Россия", city: "Волгоград" },
    dateOfBirth: "1989-05-12",
    education: "Волгоградский государственный университет, Психология",
    webSite: "https://victoria-ux.com",
    occupation: "UX-исследователь",
    interests: "Пользовательские исследования, тестирование",
    phoneNumber: "+7 900 123 45 67",
    email: "victoria.lebedeva@email.com",
    socialMedia: {
      instagram: "@victoria_ux",
      twitter: "@victoria_ux",
      linkedin: "linkedin.com/in/victoria-lebedeva",
    },
    statusText: "Глубокие исследования для лучшего пользовательского опыта",
  },
  {
    id: 92,
    status: true,
    name: "Сергей Орлов",
    // // title: "Сетевой администратор",
    avatar: "https://i.ibb.co/hYdhN34/user-avatar-42.jpg",
    location: { country: "Россия", city: "Сочи" },
    dateOfBirth: "1986-11-02",
    education: "Сочинский государственный университет, Сетевые технологии",
    webSite: "https://sergey-netadmin.com",
    occupation: "Сетевой администратор",
    interests: "Сетевые решения, безопасность",
    phoneNumber: "+7 900 123 45 67",
    email: "sergey.orlov@email.com",
    socialMedia: {
      instagram: "@sergey_netadmin",
      twitter: "@sergey_netadmin",
      linkedin: "linkedin.com/in/sergey-orlov",
    },
    statusText: "Оптимизация и защита IT инфраструктуры",
  },
  {
    id: 93,
    status: false,
    name: "Ирина Орлова",
    // // title: "Финансовый аналитик",
    avatar: "https://i.ibb.co/ws57vyR/user-avatar-43.jpg",
    location: { country: "Россия", city: "Барнаул" },
    dateOfBirth: "1990-12-14",
    education: "Алтайский государственный университет, Финансовый анализ",
    webSite: "https://irina-finanalyst.com",
    occupation: "Финансовый аналитик",
    interests: "Финансовое планирование, анализ данных",
    phoneNumber: "+7 900 123 45 67",
    email: "irina.orlova@email.com",
    socialMedia: {
      instagram: "@irina_finanalyst",
      twitter: "@irina_finanalyst",
      linkedin: "linkedin.com/in/irina-orlova",
    },
    statusText: "Оптимизация финансовых процессов для бизнеса",
  },
  {
    id: 94,
    status: true,
    name: "Роман Кузнецов",
    // // title: "Графический дизайнер",
    avatar: "https://i.ibb.co/nP4GRgS/user-avatar-44.jpg",
    location: { country: "Россия", city: "Ростов-на-Дону" },
    dateOfBirth: "1989-07-22",
    education: "Ростовский государственный университет, Дизайн",
    webSite: "https://roman-graphicdesign.com",
    occupation: "Графический дизайнер",
    interests: "Дизайн, брендинг, иллюстрации",
    phoneNumber: "+7 900 123 45 67",
    email: "roman.kuznetsov@email.com",
    socialMedia: {
      instagram: "@roman_graphic",
      twitter: "@roman_graphic",
      linkedin: "linkedin.com/in/roman-kuznetsov",
    },
    statusText: "Создаю креативный дизайн для брендов",
  },
  {
    id: 95,
    status: false,
    name: "Светлана Павлова",
    // // title: "Программист 1С",
    avatar: "https://i.ibb.co/nPp9NYs/user-avatar-45.jpg",
    location: { country: "Россия", city: "Екатеринбург" },
    dateOfBirth: "1991-10-30",
    education: "Уральский федеральный университет, Информационные технологии",
    webSite: "https://svetlana-1cprogrammer.com",
    occupation: "Программист 1С",
    interests: "1C, автоматизация бизнеса",
    phoneNumber: "+7 900 123 45 67",
    email: "svetlana.pavlova@email.com",
    socialMedia: {
      instagram: "@svetlana_1c",
      twitter: "@svetlana_1c",
      linkedin: "linkedin.com/in/svetlana-pavlova",
    },
    statusText: "Разработка и оптимизация решений на платформе 1С",
  },
  {
    id: 96,
    status: true,
    name: "Андрей Васильев",
    // // title: "Сетевой инженер",
    avatar: "https://i.ibb.co/MSz9QTL/user-avatar-46.jpg",
    location: { country: "Россия", city: "Томск" },
    dateOfBirth: "1988-09-05",
    education: "Томский государственный университет, Сетевые технологии",
    webSite: "https://andrey-networking.com",
    occupation: "Сетевой инженер",
    interests: "Сетевые решения, Wi-Fi технологии",
    phoneNumber: "+7 900 123 45 67",
    email: "andrey.vasiliev@email.com",
    socialMedia: {
      instagram: "@andrey_networking",
      twitter: "@andrey_networking",
      linkedin: "linkedin.com/in/andrey-vasiliev",
    },
    statusText: "Обеспечиваю стабильную работу сетевых инфраструктур",
  },
  {
    id: 97,
    status: false,
    name: "Дарина Смирнова",
    // // title: "Web-разработчик",
    avatar: "https://i.ibb.co/P9Q6FKd/user-avatar-47.jpg",
    location: { country: "Россия", city: "Владивосток" },
    dateOfBirth: "1992-03-11",
    education: "Дальневосточный федеральный университет, Веб-разработка",
    webSite: "https://darina-webdev.com",
    occupation: "Web-разработчик",
    interests: "JavaScript, React, CSS",
    phoneNumber: "+7 900 123 45 67",
    email: "darina.smirnova@email.com",
    socialMedia: {
      instagram: "@darina_webdev",
      twitter: "@darina_webdev",
      linkedin: "linkedin.com/in/darina-smirnova",
    },
    statusText: "Разработка современных и адаптивных веб-сайтов",
  },
  {
    id: 98,
    status: true,
    name: "Кирилл Герасимов",
    // // title: "Директор по продажам",
    avatar: "https://i.ibb.co/By7PHCZ/user-avatar-48.jpg",
    location: { country: "Россия", city: "Калуга" },
    dateOfBirth: "1986-02-09",
    education: "Калужский государственный университет, Экономика и управление",
    webSite: "https://kirill-sales.com",
    occupation: "Директор по продажам",
    interests: "Стратегии продаж, маркетинг",
    phoneNumber: "+7 900 123 45 67",
    email: "kirill.gerasimov@email.com",
    socialMedia: {
      instagram: "@kirill_sales",
      twitter: "@kirill_sales",
      linkedin: "linkedin.com/in/kirill-gerasimov",
    },
    statusText: "Руководство успешной командой продаж",
  },
  {
    id: 99,
    status: false,
    name: "Евгения Боброва",
    // // title: "HR бизнес-партнер",
    avatar: "https://i.ibb.co/4Z77nKD/user-avatar-49.jpg",
    location: { country: "Россия", city: "Воронеж" },
    dateOfBirth: "1993-05-06",
    education: "Воронежский государственный университет, Управление персоналом",
    webSite: "https://evgeniya-hr.com",
    occupation: "HR бизнес-партнер",
    interests: "Управление персоналом, корпоративная культура",
    phoneNumber: "+7 900 123 45 67",
    email: "evgeniya.bobrova@email.com",
    socialMedia: {
      instagram: "@evgeniya_hr",
      twitter: "@evgeniya_hr",
      linkedin: "linkedin.com/in/evgeniya-bobrova",
    },
    statusText: "Развиваю корпоративную культуру в компаниях",
  },
  {
    id: 100,
    status: true,
    name: "Максим Смирнов",
    // // title: "Технический директор",
    avatar: "https://i.ibb.co/HtHkN3T/user-avatar-50.jpg",
    location: { country: "Россия", city: "Москва" },
    dateOfBirth: "1985-01-25",
    education: "Московский государственный университет, Инженерия",
    webSite: "https://maxim-tech.com",
    occupation: "Технический директор",
    interests: "Инновации, технологии",
    phoneNumber: "+7 900 123 45 67",
    email: "maxim.smirnov@email.com",
    socialMedia: {
      instagram: "@maxim_tech",
      twitter: "@maxim_tech",
      linkedin: "linkedin.com/in/maxim-smirnov",
    },
    statusText: "Веду компанию к техническим успехам и инновациям",
  },
];
